Table: aktivitas_notifikasi, Non-null count: 37
Table: action, Non-null count: 0
Table: ba_serah_terima_barang_pemenuhan_qc, Non-null count: 20930
Table: asset_stag, Non-null count: 0
Table: ba_serah_terima_barang_pemenuhan, Non-null count: 897
Table: ba_serah_terima_barang_pemenuhan_aset, Non-null count: 2173
Table: ba_serah_terima_barang_pemenuhan_evidence, Non-null count: 996
Table: ba_serah_terima_barang_pemenuhan_tahapan, Non-null count: 0
Table: backup, Non-null count: 0
Table: condition, Non-null count: 21
Table: check_in, Non-null count: 1
Table: batch, Non-null count: 111
Table: data_barang, Non-null count: 0
Table: data_barang_by_flag_counter, Non-null count: 0
Table: data_barang_by_status_barang_counter, Non-null count: 0
Table: data_barang_by_status_counter, Non-null count: 0
Table: data_barang_counter, Non-null count: 0
Table: data_barang_distribusi_counter, Non-null count: 0
Table: data_barang_evidence, Non-null count: 0
Table: data_barang_keseluruhan_counter, Non-null count: 0
Table: data_barang_qc_not_pass, Non-null count: 0
Table: ekspedisi, Non-null count: 0
Table: forgot_password, Non-null count: 0
Table: gudang, Non-null count: 0
Table: heartbeat_app_version, Non-null count: 0
Table: heartbeat_schedule, Non-null count: 0
TABEL DENGAN DATA NULL: public.aktivitas_notifikasi
TABEL DENGAN DATA NULL: public.alembic_version
TABEL DENGAN DATA NULL: public.asset_backup
TABEL DENGAN DATA NULL: public.data_barang_keseluruhan_counter
TABEL DENGAN DATA NULL: public.laporan_availability_weekly
TABEL DENGAN DATA NULL: public.laporan_availability_weekly_detail_pemenuhan
TABEL DENGAN DATA NULL: public.laporan_availability_weekly_detail_penambahan
TABEL DENGAN DATA NULL: plustix.aktivitas_notifikasi
TABEL DENGAN DATA NULL: plustix.action
TABEL DENGAN DATA NULL: public.log_part_data_barang
TABEL DENGAN DATA NULL: plustix.alembic_version
TABEL DENGAN DATA NULL: plustix.asset_stag
TABEL DENGAN DATA NULL: plustix.ba_serah_terima_barang_pemenuhan
TABEL DENGAN DATA NULL: plustix.ba_serah_terima_barang_pemenuhan_aset
TABEL DENGAN DATA NULL: plustix.ba_serah_terima_barang_pemenuhan_evidence
TABEL DENGAN DATA NULL: plustix.ba_serah_terima_barang_pemenuhan_tahapan
TABEL DENGAN DATA NULL: plustix.backup
TABEL DENGAN DATA NULL: plustix.condition
TABEL DENGAN DATA NULL: plustix.check_in
TABEL DENGAN DATA NULL: plustix.batch
TABEL DENGAN DATA NULL: plustix.daata
TABEL DENGAN DATA NULL: public.pm_activity
TABEL DENGAN DATA NULL: plustix.data_barang
TABEL DENGAN DATA NULL: public.data_barang_by_flag_counter
TABEL DENGAN DATA NULL: public.ba_serah_terima_barang_pemenuhan_aset
TABEL DENGAN DATA NULL: public.ba_serah_terima_barang_pemenuhan_evidence
TABEL DENGAN DATA NULL: public.ba_serah_terima_barang_pemenuhan_qc
TABEL DENGAN DATA NULL: public.ba_serah_terima_barang_pemenuhan_tahapan
TABEL DENGAN DATA NULL: public.batch
TABEL DENGAN DATA NULL: public.check_in
TABEL DENGAN DATA NULL: public.condition
TABEL DENGAN DATA NULL: public.data_barang_by_status_counter
TABEL DENGAN DATA NULL: public.daata
TABEL DENGAN DATA NULL: public.data_barang
TABEL DENGAN DATA NULL: public.data_barang_by_status_barang_counter
TABEL DENGAN DATA NULL: public.data_barang_counter
TABEL DENGAN DATA NULL: public.data_barang_distribusi_counter
TABEL DENGAN DATA NULL: public.data_barang_evidence
TABEL DENGAN DATA NULL: public.data_barang_qc_not_pass
TABEL DENGAN DATA NULL: public.data_edc
TABEL DENGAN DATA NULL: public.ekspedisi
TABEL DENGAN DATA NULL: public.forgot_password
TABEL DENGAN DATA NULL: public.group
TABEL DENGAN DATA NULL: public.gudang
TABEL DENGAN DATA NULL: public.kelengkapan
TABEL DENGAN DATA NULL: public.heartbeat_app_version
TABEL DENGAN DATA NULL: public.heartbeat_schedule
TABEL DENGAN DATA NULL: public.kategori
TABEL DENGAN DATA NULL: public.laporan_availability_daily_detail_pemenuhan
TABEL DENGAN DATA NULL: public.kota_kabupaten
TABEL DENGAN DATA NULL: public.laporan_availability_daily
TABEL DENGAN DATA NULL: public.laporan_availability_daily_detail_penambahan
TABEL DENGAN DATA NULL: public.laporan_availability_daily_detail_stok_akhir
TABEL DENGAN DATA NULL: public.laporan_availability_daily_detail_stok_awal
TABEL DENGAN DATA NULL: public.laporan_availability_daily_detail_terpakai
TABEL DENGAN DATA NULL: public.laporan_availability_suca
TABEL DENGAN DATA NULL: public.laporan_availability_suca_pemenuhan_suca
TABEL DENGAN DATA NULL: public.laporan_availability_suca_penambahan_suca
TABEL DENGAN DATA NULL: public.laporan_availability_suca_stock_akhir
TABEL DENGAN DATA NULL: public.laporan_availability_suca_stock_awal_bulan
TABEL DENGAN DATA NULL: public.laporan_availability_suca_stock_terpakai
TABEL DENGAN DATA NULL: public.laporan_availability_weekly_detail_stok_akhir
TABEL DENGAN DATA NULL: public.laporan_availability_weekly_detail_stok_awal
TABEL DENGAN DATA NULL: public.laporan_availability_weekly_detail_terpakai
TABEL DENGAN DATA NULL: public.laporan_kerusakan_manage_service
TABEL DENGAN DATA NULL: public.laporan_kerusakan_rnw
TABEL DENGAN DATA NULL: public.laporan_pemenuhan_rnw
TABEL DENGAN DATA NULL: public.laporan_pemenuhan_suca
TABEL DENGAN DATA NULL: public.laporan_pemenuhan_rnw_mentah
TABEL DENGAN DATA NULL: public.laporan_stok_rnw
TABEL DENGAN DATA NULL: public.laporan_terpakai_rnw
TABEL DENGAN DATA NULL: public.log_barang
TABEL DENGAN DATA NULL: public.log_aktivitas
TABEL DENGAN DATA NULL: public.log_barang_evidence
TABEL DENGAN DATA NULL: public.log_heartbeat
TABEL DENGAN DATA NULL: public.master_data_barang
TABEL DENGAN DATA NULL: public.new_regional
TABEL DENGAN DATA NULL: public.menu
TABEL DENGAN DATA NULL: public.module
TABEL DENGAN DATA NULL: public.MOR
TABEL DENGAN DATA NULL: public.new_lokasi
TABEL DENGAN DATA NULL: public.new_wilayah_kerja
TABEL DENGAN DATA NULL: public.new_witel
TABEL DENGAN DATA NULL: public.notifikasi
TABEL DENGAN DATA NULL: public.notifikasi_aset
TABEL DENGAN DATA NULL: public.pemenuhan
TABEL DENGAN DATA NULL: public.part_data_barang
TABEL DENGAN DATA NULL: public.penambahan
TABEL DENGAN DATA NULL: public.penambahan_v2
TABEL DENGAN DATA NULL: public.pengirim_penerima_counter
TABEL DENGAN DATA NULL: public.permission
TABEL DENGAN DATA NULL: public.pm_activity_mapping
TABEL DENGAN DATA NULL: public.pm_detail_activity_mapping
TABEL DENGAN DATA NULL: public.pm_detail_preventive
TABEL DENGAN DATA NULL: public.pm_detail_status
TABEL DENGAN DATA NULL: public.pm_log_task
TABEL DENGAN DATA NULL: public.pm_preventive
TABEL DENGAN DATA NULL: public.pm_status
TABEL DENGAN DATA NULL: public.provinsi
TABEL DENGAN DATA NULL: public.qc_data_barang
TABEL DENGAN DATA NULL: public.qc_part_data_barang
TABEL DENGAN DATA NULL: public.regional
TABEL DENGAN DATA NULL: public.relokasi
TABEL DENGAN DATA NULL: public.relokasi_data_barang
TABEL DENGAN DATA NULL: public.role
TABEL DENGAN DATA NULL: public.role_permission
TABEL DENGAN DATA NULL: public.SLA
TABEL DENGAN DATA NULL: plustix.data_barang_by_flag_counter
TABEL DENGAN DATA NULL: plustix.data_barang_by_status_barang_counter
TABEL DENGAN DATA NULL: plustix.data_barang_by_status_counter
TABEL DENGAN DATA NULL: plustix.data_barang_counter
TABEL DENGAN DATA NULL: plustix.data_barang_distribusi_counter
TABEL DENGAN DATA NULL: plustix.data_barang_evidence
TABEL DENGAN DATA NULL: plustix.data_barang_keseluruhan_counter
TABEL DENGAN DATA NULL: plustix.data_barang_qc_not_pass
TABEL DENGAN DATA NULL: plustix.ekspedisi
TABEL DENGAN DATA NULL: plustix.data_edc
TABEL DENGAN DATA NULL: plustix.forgot_password
TABEL DENGAN DATA NULL: plustix.gudang
TABEL DENGAN DATA NULL: plustix.heartbeat_app_version
TABEL DENGAN DATA NULL: plustix.heartbeat_schedule
TABEL DENGAN DATA NULL: plustix.group
TABEL DENGAN DATA NULL: plustix.kelengkapan
TABEL DENGAN DATA NULL: plustix.kategori
TABEL DENGAN DATA NULL: plustix.laporan_availability_daily
TABEL DENGAN DATA NULL: plustix.laporan_availability_daily_detail_pemenuhan
TABEL DENGAN DATA NULL: plustix.laporan_availability_daily_detail_penambahan
TABEL DENGAN DATA NULL: plustix.laporan_availability_daily_detail_stok_akhir
TABEL DENGAN DATA NULL: plustix.laporan_availability_daily_detail_stok_awal
TABEL DENGAN DATA NULL: plustix.laporan_availability_daily_detail_terpakai
TABEL DENGAN DATA NULL: plustix.laporan_availability_suca
TABEL DENGAN DATA NULL: plustix.laporan_availability_suca_pemenuhan_suca
TABEL DENGAN DATA NULL: plustix.laporan_availability_suca_penambahan_suca
TABEL DENGAN DATA NULL: plustix.laporan_availability_suca_stock_akhir
TABEL DENGAN DATA NULL: plustix.laporan_availability_suca_stock_awal_bulan
TABEL DENGAN DATA NULL: plustix.laporan_availability_suca_stock_terpakai
TABEL DENGAN DATA NULL: plustix.laporan_availability_weekly
TABEL DENGAN DATA NULL: plustix.laporan_availability_weekly_detail_pemenuhan
TABEL DENGAN DATA NULL: plustix.laporan_availability_weekly_detail_penambahan
TABEL DENGAN DATA NULL: plustix.laporan_availability_weekly_detail_stok_akhir
TABEL DENGAN DATA NULL: plustix.laporan_availability_weekly_detail_stok_awal
TABEL DENGAN DATA NULL: plustix.laporan_availability_weekly_detail_terpakai
TABEL DENGAN DATA NULL: plustix.laporan_kerusakan_manage_service
TABEL DENGAN DATA NULL: plustix.kota_kabupaten
TABEL DENGAN DATA NULL: plustix.laporan_kerusakan_rnw
TABEL DENGAN DATA NULL: plustix.laporan_pemenuhan_rnw
TABEL DENGAN DATA NULL: plustix.laporan_pemenuhan_rnw_bs
TABEL DENGAN DATA NULL: plustix.laporan_pemenuhan_rnw_mentah
TABEL DENGAN DATA NULL: plustix.laporan_pemenuhan_suca
TABEL DENGAN DATA NULL: plustix.laporan_stok_rnw
TABEL DENGAN DATA NULL: plustix.laporan_terpakai_rnw
TABEL DENGAN DATA NULL: plustix.laporan_terpakai_rnw_bs
TABEL DENGAN DATA NULL: plustix.log_aktivitas
TABEL DENGAN DATA NULL: plustix.MOR
TABEL DENGAN DATA NULL: plustix.log_barang_evidence
TABEL DENGAN DATA NULL: plustix.log_part_data_barang
TABEL DENGAN DATA NULL: plustix.menu
TABEL DENGAN DATA NULL: plustix.log_heartbeat
TABEL DENGAN DATA NULL: plustix.master_data_barang
TABEL DENGAN DATA NULL: plustix.new_regional
TABEL DENGAN DATA NULL: plustix.new_lokasi
TABEL DENGAN DATA NULL: plustix.module
TABEL DENGAN DATA NULL: plustix.log_barang
TABEL DENGAN DATA NULL: plustix.new_wilayah_kerja
TABEL DENGAN DATA NULL: plustix.notifikasi
TABEL DENGAN DATA NULL: plustix.regional
TABEL DENGAN DATA NULL: plustix.notifikasi_aset
TABEL DENGAN DATA NULL: plustix.part_data_barang
TABEL DENGAN DATA NULL: plustix.pemenuhan
TABEL DENGAN DATA NULL: plustix.penambahan
TABEL DENGAN DATA NULL: plustix.penambahan_v2
TABEL DENGAN DATA NULL: plustix.provinsi
TABEL DENGAN DATA NULL: plustix.qc_data_barang
TABEL DENGAN DATA NULL: plustix.new_witel
TABEL DENGAN DATA NULL: plustix.qc_part_data_barang
TABEL DENGAN DATA NULL: plustix.permission
TABEL DENGAN DATA NULL: plustix.pengirim_penerima_counter
TABEL DENGAN DATA NULL: plustix.role
TABEL DENGAN DATA NULL: plustix.role_permission
TABEL DENGAN DATA NULL: plustix.st_perangkat_rusak
TABEL DENGAN DATA NULL: plustix.st_perangkat_rusak_data_barang
TABEL DENGAN DATA NULL: plustix.Sheet2
TABEL DENGAN DATA NULL: plustix.relokasi_data_barang
TABEL DENGAN DATA NULL: plustix.SLA
TABEL DENGAN DATA NULL: plustix.status_barang
TABEL DENGAN DATA NULL: plustix.relokasi
TABEL DENGAN DATA NULL: plustix.state
TABEL DENGAN DATA NULL: plustix.status
TABEL DENGAN DATA NULL: plustix.status_rma
TABEL DENGAN DATA NULL: plustix.status_relocation
TABEL DENGAN DATA NULL: plustix.stock
TABEL DENGAN DATA NULL: plustix.stock_akhir
TABEL DENGAN DATA NULL: plustix.stock_awal
TABEL DENGAN DATA NULL: plustix.t_faq
TABEL DENGAN DATA NULL: plustix.t_exsel_lisensi
TABEL DENGAN DATA NULL: plustix.t_content_notification
TABEL DENGAN DATA NULL: plustix.t_group
TABEL DENGAN DATA NULL: plustix.t_forgot_password
TABEL DENGAN DATA NULL: plustix.status_pengiriman
TABEL DENGAN DATA NULL: plustix.t_asset
TABEL DENGAN DATA NULL: plustix.t_log_inventaris
TABEL DENGAN DATA NULL: plustix.t_master_data_kategori
TABEL DENGAN DATA NULL: plustix.t_inventaris_asset
TABEL DENGAN DATA NULL: plustix.t_log_asset
TABEL DENGAN DATA NULL: plustix.t_lisensi
TABEL DENGAN DATA NULL: plustix.t_log_validasi
TABEL DENGAN DATA NULL: plustix.t_master_data_activity
TABEL DENGAN DATA NULL: plustix.t_menu
TABEL DENGAN DATA NULL: plustix.t_kategori
TABEL DENGAN DATA NULL: plustix.t_metadata
TABEL DENGAN DATA NULL: plustix.t_kategori_asset
TABEL DENGAN DATA NULL: plustix.t_module
TABEL DENGAN DATA NULL: plustix.t_notification
TABEL DENGAN DATA NULL: plustix.t_pemilik_asset
TABEL DENGAN DATA NULL: plustix.t_permission
TABEL DENGAN DATA NULL: plustix.t_role_permission
TABEL DENGAN DATA NULL: plustix.t_posisi_aset
TABEL DENGAN DATA NULL: plustix.t_role
TABEL DENGAN DATA NULL: plustix.t_status_inventaris
TABEL DENGAN DATA NULL: plustix.t_status_asset_verify
TABEL DENGAN DATA NULL: plustix.t_status_coordinate_verify
TABEL DENGAN DATA NULL: plustix.t_new_lokasi
TABEL DENGAN DATA NULL: plustix.t_status_option_asset
TABEL DENGAN DATA NULL: plustix.t_status_reject
TABEL DENGAN DATA NULL: plustix.t_ticket_eskalasi_note
TABEL DENGAN DATA NULL: plustix.t_ticket
TABEL DENGAN DATA NULL: plustix.t_ticket_eskalasi
TABEL DENGAN DATA NULL: plustix.t_ticket_details
TABEL DENGAN DATA NULL: plustix.t_ticket_status
TABEL DENGAN DATA NULL: plustix.t_ticket_eskalasi_work_logs
TABEL DENGAN DATA NULL: plustix.t_ticket_note
TABEL DENGAN DATA NULL: plustix.t_ticket_log
TABEL DENGAN DATA NULL: plustix.t_ticket_eskalasi_log
TABEL DENGAN DATA NULL: plustix.t_sub_kategori
TABEL DENGAN DATA NULL: plustix.t_user_log_aktivitas
TABEL DENGAN DATA NULL: plustix.t_user_telegram
TABEL DENGAN DATA NULL: plustix.task_tahapan
TABEL DENGAN DATA NULL: plustix.t_user_role_ticket
TABEL DENGAN DATA NULL: plustix.t_work_logs
TABEL DENGAN DATA NULL: plustix.t_validasi_asset
TABEL DENGAN DATA NULL: plustix.task_barang_evidence
TABEL DENGAN DATA NULL: plustix.task_evidence
TABEL DENGAN DATA NULL: plustix.task_barang
TABEL DENGAN DATA NULL: plustix.temp_analytic
TABEL DENGAN DATA NULL: plustix.temp_ava_suca
TABEL DENGAN DATA NULL: plustix.task
TABEL DENGAN DATA NULL: plustix.temp_pemenuhan
TABEL DENGAN DATA NULL: plustix.temp_stok_akhir
TABEL DENGAN DATA NULL: plustix.temp_stok_awal
TABEL DENGAN DATA NULL: plustix.temp_stok_awal_agg
TABEL DENGAN DATA NULL: plustix.temp_terpakai
TABEL DENGAN DATA NULL: plustix.tracking_barang
TABEL DENGAN DATA NULL: plustix.vendor
TABEL DENGAN DATA NULL: plustix.tracking_evidence
TABEL DENGAN DATA NULL: plustix.tracking
TABEL DENGAN DATA NULL: plustix.user_permission
TABEL DENGAN DATA NULL: plustix.tipe_spbu
TABEL DENGAN DATA NULL: plustix.user_role
TABEL DENGAN DATA NULL: plustix.terpakai
TABEL DENGAN DATA NULL: plustix.user
TABEL DENGAN DATA NULL: plustix.warantty
TABEL DENGAN DATA NULL: plustix.wilayah_kerja
TABEL DENGAN DATA NULL: plustix.wilayah
